import type { Metadata } from "next";
import {Container} from "@/components/container"
import {Footer} from "@/components/footer"
import { Header } from "@/components/header"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
	<head>
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1"></meta>
	</head>
      <body className={inter.className}>
	  <div>
		<Header/>
			<main className="bg-page-gradient pt-navigation-height">
				{children   }
			</main>
			<Footer/>
		</div>
		</body>
    </html>
  );
}
